services:
  app:
    build: ./app
    container_name: "${COMPOSE_NAME}.app"
    volumes:
      - ../app/:/var/www/app:cached
  nginx:
    build: ./nginx
    container_name: "${COMPOSE_NAME}.nginx"
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../app/:/var/www/app:cached
